### ISSUE TITLE
Re-roll initiatives bug

### ISSUE THREAD

**Issue by leia24** [javalent/initiative-tracker#105]
When clicking the re-roll initiative button I can't get the rolls to be less than 16 over 50 rolls.
also If I then try to manually edit one of the initiatives it won't change at all. 

I can manually enter at first opening the encounter, just not after clicking the re-roll button. I have to click the button because on starting it gives their modifier as their initiative mod. I.e orc is 1, ogre gets a -1 initiative roll

I have roll equivalent creatures together turned on
there are no errors in console.

**Comment by valentine195** [comment]
I definitely don't see this behavior:

https://user-images.githubusercontent.com/38669521/223882270-5ee7490b-4c4d-4ac9-a799-f7076f4c6070.mov

What version of the plugin are you on?

**Comment by sigrunixia** [comment]
Closing as there has been no response within a timely period. If this still is an issue, a new thread is needed.
