### ISSUE TITLE
[Feature Request] Support condition values

### ISSUE THREAD

**Issue by ekerstens** [javalent/initiative-tracker#109]
Currently, conditions added to a creature either exist or not. In pathfinder, conditions can have some value, such as "dying 2", or "wounded 1." It would be great to be able to track these values in the tool.

**Comment by sigrunixia** [comment]
> Currently, conditions added to a creature either exist or not. In pathfinder, conditions can have some value, such as "dying 2", or "wounded 1." It would be great to be able to track these values in the tool.

I'd like to question and discover more your vision of implementation. An obvious solution is create a second condition with the name and move on, but what would you like to see? No guarantees thats what would happen, but it's helpful to know it from the pathfinder gm's point of view.

**Comment by ekerstens** [comment]
My thought would be to manage it similarly to how pathbuilder and other tools do it, where in addition to being able to remove a condition, it can also be incremented/decremented with a value. For example:
![image](https://user-images.githubusercontent.com/49325583/233753316-c6baf259-3dbf-4133-96b8-1f480c74bef1.png)

**Comment by dfaggioli** [comment]
I think this is now implemented (in https://github.com/javalent/initiative-tracker/releases/tag/9.7.0, by https://github.com/javalent/initiative-tracker/commit/84b358b2a50550a969b2aa0b63389291730449cd and others).

**Comment by dfaggioli** [comment]
> I think this is now implemented (in https://github.com/javalent/initiative-tracker/releases/tag/9.7.0, by [84b358b](https://github.com/javalent/initiative-tracker/commit/84b358b2a50550a969b2aa0b63389291730449cd) and others).

(And then fixed in https://github.com/javalent/initiative-tracker/commit/28214427a6af672a63ae562351dd4761fbb2d53a, which will go into 9.7.1, AFAIUI... But whatever :-D)
