### ISSUE TITLE
[Bug] Adding custom monsters to encounter breaking statblocks

### ISSUE THREAD

**Issue by dinner-boy** [javalent/initiative-tracker#111]
I have been encountering an issue where monsters imported form either critterdb or 5etools have some of their data deleted after they are added to an encounter and the encounter started (so they need to have been in an active encounter not just listed in a note). I am listing here because it seems like an issue with the initiative tracker but it could be related to something in fantasy statblocks. I also only just started using obsidian for monsters/initiative, so I can't say that it broke for me recently. It hasn't been an issue with the built in SRD monsters.

Versions:
- Obsidian: v1.1.16
- Fantasy statblocks: 3.1.2
- Initiative Tracker: 9.2.2

I was able to recreate the problem from a fresh vault in the following way (on 2 different machines and operating systems):
1. New Vault, install fantasy statblocks and initiative tracker
2. Import a monster. I brought in a Stegosaurus from 5etools 
because it was an easy reference, but I was having this problem with the custom monsters I made in CritterDB, which I really like doing. Right after importing (before it was in an encounter), the statblock looked like it should in the beastiary: 
![Stegosaurus_base](https://user-images.githubusercontent.com/25259247/227738380-d81c9bcb-2e51-4804-9e59-873fc3e9ac9d.png)
3. Add to an encounter with the proper encounter flag, and start the encounter.
```
name: Test
creatures:
 - 3: Stegosaurus
```
4. When I click the stegosaurus in the encounter, and now in the beastiary, it has been replaced by:
![Stegosaurus_broken](https://user-images.githubusercontent.com/25259247/227738477-cef1a8bc-f90a-4300-a359-6281a3db5f51.png)
HP is gone (with some other less important stuff), I couldn't track it in the encounter. Even after the encounter was deleted, The data was still gone in the beastiary, and I need to re-import to see it again. 

I wish I was a more complete developer and I could have a go at fixing this (I live in scientific computing, so basically only python). It could be related to hit dice somehow overriding hp, but I really don't know. The data is still gone when I look at the JSON data in the beastiary.

**Comment by Sara-nox** [comment]
Same problem Armor Class disappeared and now I can't start an encounter from encounter blocks. I can just add the creatures manually in  the tracker.

**Comment by sigrunixia** [comment]
This is a bug report and a feature request. It may require looking at the import functions of https://github.com/javalent/fantasy-statblocks.

**Comment by sigrunixia** [comment]
@dinner-boy We have made some updates that have changed these mechanisms. Can you confirm if your issue still persists?
