### ISSUE TITLE
[FR]: Allowing AC to be modified during running of encounter.

### ISSUE THREAD

**Issue by namtrah** [javalent/initiative-tracker#131]
I recently played a Monster that could cast Mage Armor and I wanted to change it's AC from 12 to 15 (+3 when Mage Armor cast). But that was not possible from the IT panel on the right hand side during an encounter. The spell was cast on the 2nd round so I couldn't start with an AC of 15 until they cast it. 

Could you allow changing the AC during an encounter like it is done for HP?

**Comment by valentine195** [comment]
There's an open PR for this that adds this functionality, we are just finalizing the UI.

**Comment by sigrunixia** [comment]
Tied to #118

**Comment by valentine195** [comment]
This is done.
