### ISSUE TITLE
IT: Proposed New Readme

### ISSUE THREAD

**Issue by sigrunixia** [javalent/initiative-tracker#135]
> 🥇  Our documentation has moved to Obsidian Publish. You can find a link it *[here](https://plugins.javalent.com/initiative-tracker)*.
>
> <a href='https://www.buymeacoffee.com/valentine195' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi3.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>
---

The Initiative Tracker plugin for [Obsidian](https://obsidian.md) allows you to keep track of initiative and turn order during combat encounters in tabletop role playing games.

With this plugin, you can easily add creatures and NPCs to the initiative tracker, and track their health, armor class, and other stats. The plugin also calculates experience points for creatures, and supports both custom and SRD creatures from the [Fantasy Statblocks](https://github.com/javalent/fantasy-statblocks) plugin.

## Features
- Easily add and remove creatures to the encounter
- Input creature name, HP, AC and initiative
- Calculate creature XP based on challenge rating
- Group identical creatures together to simplify the encounter
- Set creature display names to differentiate identical creatures
- Supports dice rolls to add random amounts of creatures
- Keep track of creature HP, AC, and status
- Sort creatures by initiative automatically
- Add arbitrary number of encounters in one block
- Automatically save and load encounters
- And much, much more...

### Quickstart

- Install the Initiative Tracker plugin in Obsidian.
- Open a note where you want to keep track of your encounter.
- Create a code block with the language set to \`\`\`encounter.

````yaml
```encounter
name: Example
creatures:
 - 3: Goblin
```
````

- Add creatures to the encounter by name, dice roll, or bestiary entry.
- Launch the encounter by clicking on the play button, and start tracking initiative.

Check out the **[plugin documentation](https://plugins.javalent.com/initiative-tracker)** for more detailed instructions and examples.

## Support

If you encounter any issues, want to give back and help out, or have suggestions for new features, please file an issue on the [GitHub repository](https://github.com/valentine195/obsidian-initiative-tracker/issues).

### TTRPG plugins

If you're using Obsidian to run/plan a TTRPG, you may find my other plugins useful:

-   [Obsidian Leaflet](https://github.com/valentine195/obsidian-leaflet-plugin) - Add interactive maps to Obsidian notes
-   [Dice Roller](https://github.com/valentine195/obsidian-dice-roller) - Inline dice rolling for Obsidian
-   [Fantasy Statblocks](https://github.com/valentine195/obsidian-5e-statblocks) - Format Statblocks inside Obsidian

**Comment by sigrunixia** [comment]
You added the Kofi link via javascript I think? So can't add it here in the draft. The sponsor and funding stuff is everywhere, and there will be Kofi links on the publish (Just haven't added them yet :) )

**Comment by sigrunixia** [comment]
Also is plugins-dev the final subdomain? Not sure if it means plugins development as in... its your plugin page, or as the website is under development.

**Comment by valentine195** [comment]
No I intend to move it to plugins.javalent.com, I put it under dev just in case publish didn't work out. I'll move it today

**Comment by sigrunixia** [comment]
Updated this draft to include the Kofi HTML Link and fixed the links to the publish page.
