### ISSUE TITLE
[Bug] 9.8.0 bug report

### ISSUE THREAD

**Issue by SondreElg** [javalent/initiative-tracker#148]
Seems like merge conflicts caused a lot of problems for this release

# Max HP damage
~~Cannot input m into HP field, so functionality can't be tested~~
Token was missing in HP field input validation

# Temp AC change
~~Can input into field, but there is no change to AC~~
AC argument was missing in call to tracker.doUpdate()

# Status field
Attempting to apply a custom status adds "undefined" to the status list.
If an even number of custom statuses are added, they are applied then instantly relieved when finalizing the operation.

**Comment by valentine195** [comment]
@SondreElg hey I'm pushing a fix, but I can't recreate the status error

**Comment by valentine195** [comment]
It was a bit of a mess trying to clean up those two PRs because I left them open so long, my bad!

**Comment by valentine195** [comment]
can you test 9.8.1 please

**Comment by SondreElg** [comment]
Same bug appears in 9.8.1

\- Start an encounter
\- Add "a" (or any other non-existing status) as status
= "undefined" is added to status list
\- Apply
= "undefined" status is added
= Log shows "Name took  status"

\- Repeat but add an even number of statuses
= No status is added
= Log shows "Name took  status" "Name relieved of status undefined"

**Comment by valentine195** [comment]
Oh I see - I thought by custom you meant one defined in settings

**Comment by SondreElg** [comment]
I can see where the confusion stems from.
Perhaps "improvised status" is a better term for it.
