### ISSUE TITLE
[Feature]: Show Friendly Creatures in Encounter Block Render

### ISSUE THREAD

**Issue by ryanvilbrandt** [javalent/initiative-tracker#158]
> Thank you for submitting a request! 
>
> Please answer the following carefully to help us triage implementation priority appropriately. 

# Summary
When marking a creature friendly, in the resulting in-notes block, there is no heart symbol like there is in the Initiative Tracker once the encounter has been initiated.
![image](https://user-images.githubusercontent.com/5972092/235315205-028fce92-5b73-42c0-aca7-3a6bad1ac68c.png)
![image](https://user-images.githubusercontent.com/5972092/235315215-9d887f13-2f0d-4837-b7c9-1c75fc0ab07b.png)

## Detailed Description

Add the heart symbol to friendly creatures in the encounter block render.

## Context and Use Case

It would be helpful to delineate at a glance who in an encounter is a helpful NPC and who is a baddy to beat. Right now, I have what looks like a very long list of bad guys, but it would be nice to tell them apart.

## Your Environment

* Obsidian Version used: v 1.1.16
* Obsidian Installer used: v 1.1.16
* Operating System and version (desktop or mobile): Win 10 Desktop

## Are you willing to personally help out on this project, such as design, documentation, coding, project management, etc? 
(Bold One) Yes / **No**

**Comment by sigrunixia** [comment]
Related to #157.

**Comment by valentine195** [comment]
This was closed in 78ca7b40253bc36bc9902d9a1d7a661560dfb08f
