### ISSUE TITLE
No encounters created. Please check your syntax

### ISSUE THREAD

**Issue by umiaki** [javalent/initiative-tracker#16]
Hi
is it just me or did the encounter plugin stopped working?
Does not work using even the readme encounter:
```encounter
name: Example
creatures:
 - 3: Goblin
```
-> No encounters created. Please check your syntax and try again.

**Comment by valentine195** [comment]
Please try 4.0.1. This issue was due to the fact that no players you have created were assigned levels - should be fixed now, though.
