### ISSUE TITLE
[Bug]: Players not showing up in initiative tracker despite being info being added in settings. (windows 11)

### ISSUE THREAD

**Issue by R1k0ch3t3** [javalent/initiative-tracker#160]
The bug tracker is **ONLY** used for reporting bugs.

## What are the A-to-Z Steps to Reproduce your Bug?

1.
2.
3.
4.

**Comment by R1k0ch3t3** [comment]
Here is a screenshot of my attempt.  Note the missing character on the righthand side, with only the wolves appearing
![image](https://user-images.githubusercontent.com/132167459/235323056-26022caa-450b-4699-9a5d-bf9b843cede5.png)

**Comment by sigrunixia** [comment]
@R1k0ch3t3 

Can you also post the encounter code-block?
