### ISSUE TITLE
Bug: IT is not updating player notes

### ISSUE THREAD

**Issue by sigrunixia** [javalent/initiative-tracker#176]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Notes that are attached to a player, the YAML should update in response to the player's status and edits in an encounter.

## Initial Attachment
1. When a note is attached to a player it does not add the YAML entries to the player note.
2. When the YAML entries are added to the player note, they do reflect within IT settings. They are reflected in sidebar when encounter first starts.

No matter what, IT is not writing YAML data to notes.

## During Encounter

1. Declare party will be in encounter. The party members must have notes attached to her 
2. Edit health, initiative, modifier, level, etc while keeping an eye on the note.
3. The note does not update in response to any edits to HP, or any application of damage, etc. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.2.8 and 1.2.7

### Plugin Version

Both release and 10.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

No clue. :( No error messages either.

**Comment by valentine195** [comment]
This is just one-way

**Comment by sigrunixia** [comment]
I can document this as such, but there have been some users who had intermittent errors when attempting to edit the player data when a note is attached. 

![image](https://user-images.githubusercontent.com/68425372/236706484-b7995e85-5f67-49ad-9bae-ebd4687bb9dc.png)
