### ISSUE TITLE
[Bug]: Player View Formatting Issue

### ISSUE THREAD

**Issue by NyteshadeXT** [javalent/initiative-tracker#189]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Anticipating that the Player View for Initiative Tracker would show in typical column format of Player/Enemy Name, Health, Status.

### Current behaviour

All columns of information appear in the Name column of the player view.   See screenshot of player view.

![](https://cdn.discordapp.com/attachments/925322341502812222/1110679999662538832/image.png)

### Reproduction

1. Disabled all obsidian plugins.
2. Restarted obsidian.
3. Reinstalled obsidian with most current installer.
4. Created a fresh obsidian vault prior to update of Initiative Tracker.  Initiative Tracker is in version  9.11.1 in this new install.  Reviewed player view and it behaves as expected.
![image](https://github.com/javalent/initiative-tracker/assets/126894135/67fa9017-1ab5-4600-80aa-57e2c4ab0870)
5. Updated Initiative Tracker to version 11.1.6.  Player view returns to incorrect format.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

v1.3.3

### Plugin Version

11.1.6

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Only reverting to an earlier version of Initiative Tracker has worked to fix the issue so far.

**Comment by valentine195** [comment]
Does this happen on the default theme?

**Comment by NyteshadeXT** [comment]
Yes.  Sorry if I didn't mention it, but I did revert to default theme and it was still happening.  The only time I didn't have an issue was when I was on the older version.

**Comment by NyteshadeXT** [comment]
Completely deleted the ITS Theme and restarted Obsidian.  This corrected the issue.

**Comment by NyteshadeXT** [comment]
Yes.  However, updating ITS with the recent theme changes seems to also solve the problem.  My guess is the Alternate Theme Styling snippet is causing a conflict.
