### ISSUE TITLE
🐞Missing XP icon when using ITS theme

### ISSUE THREAD

**Issue by brunomesqu** [javalent/initiative-tracker#223]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

From what I have noticed by watching Youtube videos or seeing the plugin run in the past, I expected to see an XP icon next to the total XP value of the encounter

### Current behaviour

I notice that when using the ITS theme, right next to the XP value of the encounter, where it would be expected to show the XP icon (as I have seen on Youtube videos) I get only a blank square.

### Reproduction

1. Install fantasy stat blocks plugin
2. Install ITS theme
3. Install initiative tracker plugin
4. Create a sample encounter adding any amount of creatures from the Fantasy Statblocks.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.13

### Plugin Version

12.2.3

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
@brunomesqu can you show me what the XP icon looks like in the YouTube videos?

**Comment by brunomesqu** [comment]
Sure thing! This is a print from Josh Plunkett's video on the initiative tracker
![image](https://github.com/javalent/initiative-tracker/assets/92873888/70450e71-1848-4dbc-91c6-58c5bd1b92e8)

Here's how it looks on my end:
![image](https://github.com/javalent/initiative-tracker/assets/92873888/8d1f117f-8e9d-4874-9d79-00c95d5401d4)

**Comment by valentine195** [comment]
I think this might have actually been from the ITS theme… let me ask

**Comment by valentine195** [comment]
I confirmed with the author of the ITS theme that this icon was added by them; it might be worth opening a feature request on their GitHub page requesting a toggle to enable it.

**Comment by SlRvb** [comment]
If the icon is missing, you need the [encoded icon css snippet](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Encoded%20Icons.css) installed for the icon to show up.

**Comment by brunomesqu** [comment]
> If the icon is missing, you need the [encoded icon css snippet](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Encoded%20Icons.css) installed for the icon to show up.

Solved, thank you!
