### ISSUE TITLE
Updating Frontmatter for a PC makes the SideBar increment HP weirdly 

### ISSUE THREAD

**Issue by namtrah** [javalent/initiative-tracker#225]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When I change the HP in a characters MD frontmatter, I expect that the IT sidebar tracker would modify the value to what I set.

### Current behaviour

It seems to increment the total HP randomly (or maybe adding the difference I made to the number) IDK. But it defintely doesn´t work.

### Reproduction

Start an encounter in the IT Sidebar with a player whose HP/AC, etc values are updated through the frontmatter of a Note (which was previously correctly set). 

Then update the frontmatter (via the Properties ⬆️   and ⬇️  keys.

The value (HP in this case) wildly differs.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

	Obsidian version: v1.4.13 	Installer version: v1.4.13

### Plugin Version

12.1.4

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Fixed in #226
