### ISSUE TITLE
🐞 Pathfinder XP calc doesn't work when players are different levels

### ISSUE THREAD

**Issue by scooper4711** [javalent/initiative-tracker#244]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

A PF2E party where one player is one level is lower than the others. When calculating the XP and encounter budget/threat, the average level of the players (rounded up) should be used. 

### Current behaviour

I have a PF2E player party where one player is one level lower than the others. When calculating XP and encounter budget/threat level, all creatures have 0XP and the threat level is trivial

### Reproduction

See attached vault.
1. open encounter builder
2. select any monsters, e.g. Jungle Drake and Dragon Pillar.
3. Select the party "XP does not work" - XP is not calculated
4. Select the party "XP works" - XP is calculated

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.5.3

### Plugin Version

12.4.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by scooper4711** [comment]
[xp-bug.zip](https://github.com/javalent/initiative-tracker/files/13903878/xp-bug.zip)
Sample vault

**Comment by scooper4711** [comment]
Fixed in version 12.4.3

**Comment by valentine195** [comment]
user indicated its closed
