### ISSUE TITLE
🐞 "Add to Encounter" Button not working

### ISSUE THREAD

**Issue by pbborsdorf** [javalent/initiative-tracker#308]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

![grafik](https://github.com/user-attachments/assets/2a9f9578-53e9-4699-bb8f-5d64dd9c9ff8)

Click Button "Add to Encounter" to add the creature.

### Current behaviour

Button is showing the forbidden sign, unable to click. Manually adding Creatures in the block does add them.

### Reproduction

Have TTRGP Statblocks enabled - synced to Initative tracker. (Also Level up A5E statblocks installed and working). Open Iniative Tracker Pane, click "+ Add Creature", choose creature.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.7.5

### Plugin Version

13.0.16

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Might be a very basic error on my part but I can't figure it out and didn't find any other reports on this. Sorry if this a waste of time!

**Comment by tayraye22** [comment]
Hi did you find out what was causing this issue? I am also having it
