### ISSUE TITLE
[Feature Request] Search Capability for Combatant View

### ISSUE THREAD

**Issue by scottTomaszewski** [javalent/initiative-tracker#65]
During prep time its sometimes useful to be able to pull up the statblock just for references purposes and it would be useful to do so without needing to add the statblock to a note.  The Initiative Tracker already has a Combatant view which I really like and I would like to be able to type in the name of a creature and have that statblock show in that window.  

Currently my process is to add a statblock to the note 

    ```statblock
    monster: Goblin
    ```
and then render it, check it, then delete it, but if I could just pull it up in a sidebar that would be ideal.

Thanks! I love these plugins!

**Comment by g-bauer** [comment]
Can you give more detail on what you want to do? 

1. Do you want the combat view (without having to create an encounter) with a search option for all monsters, or 
2. a search option for monsters in an encounter?

I think, point (1) would be thematically more suitable in the stat-block plugin.

**Comment by scottTomaszewski** [comment]
If we are understanding each other properly, yes - I think the first option is what I was thinking.  I think the request is something like "ability to view monster statblocks in an ephemeral way; without needing to create a formal `statblock` nor `encounter`"

I can open a different ticket in the stat-block plugin repo if that is more appropriate :)

**Comment by g-bauer** [comment]
I mean - that's for Jeremy to decide but IMHO this would be better suited as a feature of the 5e-statblocks plugin. One could reuse (copy) the component from this plugin and add a search field.
