### ISSUE TITLE
Inconsistant Difficulty between Encounter Blocks.

### ISSUE THREAD

**Issue by Bugmaniac71** [javalent/initiative-tracker#70]
![issue](https://user-images.githubusercontent.com/5765768/192756474-6bb72740-1d0f-456b-b645-54743654a513.png)

If I create two encounters. Both are exactly the same just one is a normal encounter and the other is via an encounter table, the difficulties arent calculated incorrectly within the table version .(see screenshot).

Encounter code is below:

```encounter-table
name: Example 1
creatures:
 - Hobgoblin
 - 3: Goblin
```

```encounter
name: Example 2
creatures:
 - Hobgoblin
 - 3: Goblin
```

**Comment by Mazarkus** [comment]
I'm also observing this issue.  When the encounter is in a table, it is always using the same daily XP thresholds no matter how many players of different levels I include, however when the encounter gets added to the active initiative tracker it seems to be calculated correctly and matches the equivalent encounter in dndbeyond

**Comment by kruber312** [comment]
Hi, I'm also encountering this error. In my case no matter the players or party I add to the encounters it takes all the players created to calculate the threshold.
![image](https://user-images.githubusercontent.com/124858369/217722041-eefb3a11-b2c4-406a-a79c-bafcb2b3337d.png)
In this case all the characters are lvl 3..

When I add it to the Initiative tracker it works correctly.

**Comment by valentine195** [comment]
I believe this issue should be fixed in the latest release. Can someone verify?

**Comment by valentine195** [comment]
I am closing this, if it is still occurring for some people please open a new issue.
