### ISSUE TITLE
AC is not displayed if it contains text

### ISSUE THREAD

**Issue by scottmc42** [javalent/initiative-tracker#71]
Version 8.0.11

The AC field will only display if it is a numeric value. If it contains text, then is does not show in the initiative grid, nor in the 5e template below.

This field needs to be able to strip out text characters so that the value can be shown in the grid, and display the complete string in the 5e template.

For instance, I created a monster whose AC is "14 (natural armor)" and it would not show up in either location, but if I just put in "14" it worked as expected.

This is not an issue in 5e statblock. The same creature show up as expected if I just pull them up via `statblock`.

Although it looks like the 5e statblock importer drops the text so it's not an easily found problem. Pulling the MM from 5eTools, "Archmage" should have an AC of "12, (15 with mage armor)", but when I look at the JSON for that entry, statblock only has "12". So that would be a different issue/feature enhancement.

**Comment by valentine195** [comment]
Is this still an issue? AC should support strings as of 9.1.1 https://github.com/javalent/initiative-tracker/releases/tag/9.1.1

**Comment by scottmc42** [comment]
I spoke too soon. I was still using an older version of the add-on.
I upgraded to the latest version and was able to see the AC including text in both the initiative window and the stat block window.
