### ISSUE TITLE
Cannot close creature view statblock (bottom right corner) once opened.

### ISSUE THREAD

**Issue by Bugmaniac71** [javalent/initiative-tracker#73]
Cannot close creature view statblock in the Initiative Tracker (bottom right corner) once opened.
Clicking on the X to close it does nothing.

**Comment by SondreElg** [comment]
I've tried to replicate the problem, but can't seem to do it.
Would you mind sharing which version you have of the various tools involved?

e.g (for me):

Obsidian: 1.0.3
Initiative Tracker: 8.1.0
TTRPG Statblocks: 2.22.0

**Comment by valentine195** [comment]
Clicking the X closes the open creature. You can close the view by right clicking the dragon icon.

**Comment by Bugmaniac71** [comment]
Ah perfect, thank you!

**Comment by Bugmaniac71** [comment]
Sorted now thanks.
