### ISSUE TITLE
Display Name and and Hidden state not saving on "Save Encounter"

### ISSUE THREAD

**Issue by cjolson** [javalent/initiative-tracker#76]
When I prep for a session, I like to create my encounters ahead of time and _Save_ them so they are quick to _Load_ later. However, When I reload an encounter, it does not save the Hidden state or the Display Names. This can be tricky since I need to re-hide my hidden creatures and re-name the Display Names mid-session instead of jumping right in.

**Comment by valentine195** [comment]
Is this still occurring? @cjolson
