### ISSUE TITLE
[Bug] Dragging to change init order not working

### ISSUE THREAD

**Issue by apolaine** [javalent/initiative-tracker#79]
Obsidian v1.0.3
Initiative Tracker: v8.1.2
Mac OS Ventura 13.0
Default theme

Dragging to manually change initiative order no longer works. Additionally, trying to do so seems to change the init number of the PC.

**Comment by valentine195** [comment]
Is this still an issue?

**Comment by sigrunixia** [comment]
@apolaine Tagging name for added questioning.

**Comment by apolaine** [comment]
No, seems to be resolved now.
