### ISSUE TITLE
Tracker becomes laggy/stuttery after manually adding creatures

### ISSUE THREAD

**Issue by XintakXVI** [javalent/initiative-tracker#85]
Hi there! Not sure if anyone else experiences this problem, but I didn't see any issue for it.

After I manually add a creature to an active encounter (not necessarily started yet), the list begins to stutter when scrolling, and seems to get a bit worse each time I add a creature.
Moving the tracker into a new tab seems to solve the stuttering during scroll, but actions like dragging to reorder are still laggy.
The scroll stuttering returns after putting the tracker back in the sidebar.

Let me know if anything else is required or would be helpful!

**Comment by rafaelxvr** [comment]
Hello! Same thing happening with me.
