### ISSUE TITLE
Roll HP for creatures when using 5e statblocks

### ISSUE THREAD

**Issue by nrabins** [javalent/initiative-tracker#89]
When beginning an encounter, it would often be useful if the creatures' HPs were rolled according to their hit dice in their associated statblock instead of just using their written HP value.

For the UX, this could be available in three ways:
- In the three dot menu, an option to "Re-roll HP". This would roll the HP for all applicable creatures. Alternatively, the "Reset HP & Status" option could have a follow-up choice (like "Switch Party" does): "Using Average HP" or "Using Hit Dice".
- In the apply HP/status affects pane, a button (heart icon?) that would roll the HP for the selected creature(s).
- An opt-in setting to "roll HP using statblock hit dice" in the plugin's settings.

If this is an existing feature, please let me know, as I haven't been able to figure out how to do it.

Thank you for your consideration and your hard work!

**Comment by valentine195** [comment]
I added this recently!
