### ISSUE TITLE
[Bug] Combatant update when clinking creature's name

### ISSUE THREAD

**Issue by axistos** [javalent/initiative-tracker#96]
Hello, and thank you for the awesome plugin.

I have encountered a strange behavior that seems like a bug.
From what I understand, when I click on a creature's name, the creature's view should be opened in the Combatant window.
However, this only works half the time. Sometimes, when the creature's name is clicked, the table for applying damage and status effects is opened instead. This table should open when clicking on the creature's HP display, not its name.

I cannot pinpoint when the first (creature's view) and second (damage and status table) behavior is occurring, and it seems random to me.
I am using obsidian v1.0.3, and I have installed the plugin through obsidian and updated it to version 8.1.6.
Am I doing something wrong, or is this a bug?

Thank you!

**Comment by achronister** [comment]
Similar issue. Updated to latest plugins (using Dice roller, Initiative Tracker, and Statblock plugins). Encounter has 4 individually-listed 'Ghoul' creatures (differing assigned HP). Start encounter. Ghouls get an adorned name, like 'Ghoul 1', 'Ghoul 2', etc. Clicking a combatant used to show full 'generic' statblock info in the combatant view. Now it seems that the name link to the statblock entry is broken.
Formerly with Dice roller 8.6.1, Initiative tracker 7.5.0, Statblock 2.14.10 (my prior setup before getting latest), this worked flawlessly.
Time Machine to the rescue.  :)
Haven't had a chance to look at the code at all (your dice roller is waaay more advanced than mine, so I've punted my nextjs "DM" app and moved to Obsidian + your plugins - awesome sauce).

**Comment by valentine195** [comment]
Is this still occuring?

**Comment by axistos** [comment]
No, it's good now! Thank you for all your effort!

**Comment by sigrunixia** [comment]
Closing this as it is resolved! Happy Encounters for you, and unhappy for your players. 🗡️  :)
